name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential g++ make libboost-all-dev wget python3-pip
        pip install pytest
        
    - name: Download Crow
      run: |
        mkdir -p include
        wget https://github.com/CrowCpp/Crow/releases/download/v1.0%2B5/crow_all.h -O include/crow.h

    - name: Build project
      run: |
        make build

    - name: Run unit tests
      run: |
        make unit-test

    - name: Run integration tests
      run: |
        make integration-test

    - name: Run E2E tests
      run: |
        python3 -m pytest tests/e2e_test.py

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/snake-game:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/snake-game:${{ github.sha }}
        
    - name: Deploy to server (SSH)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/snake-game:${{ github.sha }}
          docker stop snake-game || true
          docker rm snake-game || true
          docker run -d -p 8080:8080 \
            --name snake-game \
            --restart always \
            ${{ secrets.DOCKER_HUB_USERNAME }}/snake-game:${{ github.sha }}